[toolchain]
anchor_version = "0.28.0"
solana_version = "1.18.22"

[workspace]
members = [
  "programs/autobahn-executor"
]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
autobahn_executor = "AutobNFLMzX1rFCDgwWpwr3ztG5c1oDbSrGq7Jj2LgE"