app = "router-eclipse"
primary_region = "fra"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  dockerfile = 'bin/autobahn-router/eclipse/Dockerfile'

[experimental]
  cmd = ["autobahn-router", "/usr/local/bin/template-config-eclipse.toml"]

[[vm]]
  size = "shared-4x"
  memory = "8gb"

[[restart]]
  policy = "always"
  retries = 10

[metrics]
  port = 9091
  path = "/metrics"