[package]
name = "cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
tokio = { workspace = true }
anyhow = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
autobahn-executor = { path = "../../programs/autobahn-executor" }
router-lib = { path = "../../lib/router-lib/", version = "0.0.1" }
router-config-lib = { path = "../../lib/router-config-lib/", version = "0.0.1" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bytemuck = "1.16.1"

reqwest = { workspace = true, features = ["json"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
atty = "0.2.14"
bincode = "1.3.3"
base64 = "0.22.1"
